name: Registry

on:
  push:
    branches:
      - master
jobs:
  poc:
    runs-on: ubuntu-latest
    steps:
      - uses: oprypin/find-latest-tag@v1
        with:
          repository: zzxwill/derrick-go  # The repository to scan.
          releases-only: true  # We know that all relevant tags have a GitHub release for them.
        id: octokit  # The step ID to refer to later.
      - name: Get the version
        id: get_version
        run:
          echo ::set-output name=VERSION::hhhh-${{ steps.octokit.outputs.tag }}
      - run: |
          version=${{ steps.get_version.outputs.VERSION }}
          echo $version
